### PR TITLE
QA: subtler hover transition

### LINKED ISSUE #175: Update hover effect so it's more "on-brand" and subtle

### PR DESCRIPTION
**Pull request by nahbee10**
### Description

- add transition to hover state change 
- make hover gradient color more transparent to make the layer more subtle

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [x] Update to an existing feature

### Motivation for PR

Closes #175 
QA ticket from Notion([link](https://www.notion.so/garden3d/There-should-be-a-graceful-on-brand-transition-for-the-hover-state-636ae69f018242658169ebc847bd9ab4))

### How Has This Been Tested?

Tested with [preview](https://sanctu-dot-776f11xpu-sanctucompu.vercel.app/) on desktop Chrome/Safari

### Applicable screenshots

transition on dark layer : https://www.loom.com/share/8ad1ff670be54ff2912f4fc729b53f32
transition on light layer :

### CODE REVIEW

**Comment by mokaymokay** [comment]
Looks great so far!!

**Comment by mokaymokay** [comment]
I'm not 100% digging the overlay--light / dark text version.. i think the white background has too much of a contrast with the black text, and a transparent light gray may look better. what do you think? 
Screen Shot 2023-01-31 at 1 30 34 PM

**Comment by nahbee10** [comment]
> I'm not 100% digging the overlay--light / dark text version.. i think the white background has too much of a contrast with the black text, and a transparent light gray may look better. what do you think? 

Grey layer makes texts hard to read on darker images(as screenshots below) but I think in those cases editors can switch to black bg + white text color(dark theme)! I changed the bg gradient to the light grey one and pushed the commit :) @mokaymokay 

- Light grey bg + black text on dark image
Screen Shot 2023-01-31 at 6 09 09 PM

- white bg + black text on dark image
Screen Shot 2023-01-31 at 6 09 30 PM

**Comment by mokaymokay** [comment]
Yep, I was thinking the same about using the white text on a dark background. Can you please set the theme for all works used on the home page in Contentful according to the background color, then re-deploy? For example, white text for both Loupe This images linked above and this Tend image below, etc. I trust your judgment.

Screen Shot 2023-02-01 at 12 37 01 PM

It would be helpful for Elie or other people QAing to see if the current styles are working well for all images and if we need to make any adjustments!

**Comment by nahbee10** [comment]
> Sorry I noticed something while doing mobile/tablet QA. I think we might need to use the styling you previously set (white background) for mobile/tablet, because the text sometimes crosses different background colors, i.e. Swell image. Usually this is easily fixable by using another version of the image for mobile, but since we didn't implement that ability here, let's make the background white so the black text stands out more as an easy fix.

@mokaymokay all good! Just pushed reverted version ;)

**Comment by nahbee10** [comment]
@mokaymokay all changes(removing bg overlay[[Notion thread](https://www.notion.so/garden3d/I-d-like-to-see-what-the-site-would-look-like-with-no-overlay-on-hover-at-all-60edd900435d45bca7249f8cde4d9ac8)] / external caption for mobile screen[[Twist thread](https://twist.com/a/133876/ch/552738/t/4052838/c/81576710)]) were made and ready for final review. 
[PREVIEW is here](https://sanctu-dot-8m8tgsajb-sanctucompu.vercel.app/).

**Pull request merged**
