### PR TITLE
Don't pre-load every video

### PR DESCRIPTION
**Pull request by limsohee1002**
### Description:
- remove autoplay of video
- download the video when the slide is active

Note:
There are videos that are missing poster image. If you see the white background in between slides, that is because the poster image is not available.

### CODE REVIEW

**Comment by hhff** [comment]
Can you please confirm that when you open the inspector and reload the page (using Empty Cache and Hard Reload), none of the videos start loading?

Here's what happens in the current site (filter by `.mp4` in Network panel):
image

**Comment by hhff** [comment]
See how it says `109 MB transferred`? It should only say ~5mb transferred

**Comment by limsohee1002** [comment]
@hhff I just record video to show only one video is loading here https://www.loom.com/share/818c03e3bd974844a7e3ba53f8a2562f

With one video loading it said `11.0MB transferred` 
image

**Comment by hhff** [comment]
@limsohee1002 

> I just record video to show only one video is loading here

That's a good start, however, as per the ticket, the first video should only load when it is in viewport: https://ottball.com/lazy-loading-video/

Other videos should load in the same way, when the user clicks to advance!

**Comment by limsohee1002** [comment]
> @limsohee1002
> 
> > I just record video to show only one video is loading here
> 
> That's a good start, however, as per the ticket, the first video should only load when it is in viewport: https://ottball.com/lazy-loading-video/
> 
> Other videos should load in the same way, when the user clicks to advance!

ohhhh got it! I will add that function!

**Comment by limsohee1002** [comment]
@hhff here is an update! https://www.loom.com/share/3a34d02b6828470b937fc257ef10ccd5

**Comment by limsohee1002** [comment]
@hhff Rebased :)

**Pull request merged**
