### PR TITLE
Chore: add and run prettier, add PR template

### LINKED ISSUE #177: Chore: Install prettier in CI
Install prettier in deploy action and run it for entire codebase

### PR DESCRIPTION
**Pull request by nahbee10**
### Description

- move husky pre-commit command from package.json to separate husky settings file since it is required to do so from husky v7 -> prettier and lint-stage command was there, but not working because of this
- run prettier to all file
- add PR template 

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [x] Update to an existing feature

### Motivation for PR

Closes #177 

### How Has This Been Tested?

Tested when commit and push new changes for this branch

### CODE REVIEW

**Review by mokaymokay — COMMENTED** [review]
The [existing husky config](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/) in `package.json` should already work by linting when the dev adds a commit to those files. i don't think we need to change those.

**Comment by nahbee10** [comment]
> The [existing husky config](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/) in `package.json` should already work by linting when the dev adds a commit to those files. i don't think we need to change those.

@mokaymokay I was also curious about that and I think it is because husky configuration needs to happen in `.husky/pre-commit` not in `package.json` ([related stackoverflow thread](https://stackoverflow.com/a/68761163))! It worked once I moved the command to the .husky config file.

**Comment by mokaymokay** [comment]
> > The [existing husky config](https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/) in `package.json` should already work by linting when the dev adds a commit to those files. i don't think we need to change those.
> 
> @mokaymokay I was also curious about that and I think it is because husky configuration needs to happen in `.husky/pre-commit` not in `package.json` ([related stackoverflow thread](https://stackoverflow.com/a/68761163))! It worked once I moved the command to the .husky config file.

@nahbee10 ahh got it! sounds good, thanks!

**Review by mokaymokay — APPROVED** [review]
LGTM nahee, definitely ✨prettier ✨

**Pull request merged**
